[package]
name = "rusticata"
version = "0.1.0"
description = "Glue layer for loading Rust parsers in Suricata"
license = "LGPL-2.1+"
keywords = ["Suricata","IDS","TLS","SSL","protocol","parser","nom"]
homepage = "https://github.com/rusticata/rusticata"
repository = "https://github.com/rusticata/rusticata.git"
authors = ["Pierre Chifflier <chifflier@wzdftpd.net>"]
edition = "2018"

# [lib]
# crate-type = ["dylib"]
# # crate-type = ["staticlib"]

[dependencies]
libc = "0.2.0"
log = "0.4.6"
nom = "5.0"
enum_primitive = "0.1.0"
itertools = "0.8"
md5 = "0.7"
der-parser = "3.0"
dhcp4r = "0.2"
dns-parser = "0.8"
ipsec-parser = "0.5.0"
kerberos-parser = "0.4"
ntp-parser = "0.4"
openvpn-parser = "0.4"
radius-parser = "0.3"
snmp-parser = "0.5"
ssh-parser = "0.3"
tls-parser = "0.9"
x509-parser = "0.6"
